# Name must match global.argoProject in agent-devstack/agent-stack.
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    argocd.argoproj.io/rootproject: "true"
spec:
  description: Agent local development environment

  sourceRepos:
    - '*'

  sourceNamespaces:
    - '*'

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
