{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}-api
  labels:
    {{- include "agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
