{{- if and .Values.vault.secretsEnabled .Values.egress.enabled }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: egress-api-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshPeriod: 12h0m0s
  vaultSecretDefinitions:
    - connection:
        address: {{ .Values.vault.address }}
      authentication:
        path: {{ .Values.vault.authPath }}
        role: {{ .Values.vault.role }}
        serviceAccount:
          name: default
      name: secret
      path: {{ .Values.vault.secretPath }}/egress-api
  output:
    name: egress-api-secret
    stringData:
      connectionString: {{`'{{ .secret.connection_string }}'`}}
      treKeycloakClientSecret: {{`'{{ .secret.tre_keycloak_client_secret }}'`}}
      dataEgressKeycloakClientSecret: {{`'{{ .secret.data_egress_keycloak_client_secret }}'`}}
      s3AccessKey: {{`'{{ .secret.s3_access_key }}'`}}
      s3SecretKey: {{`'{{ .secret.s3_secret_key }}'`}}
      encryptionKey: {{`'{{ .secret.encryption_key }}'`}}
      encryptionBase: {{`'{{ .secret.encryption_base }}'`}}
      demoModeDefaultPassword: {{`'{{ .secret.demo_mode_default_password }}'`}}
    type: Opaque

---

apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: egress-ui-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshPeriod: 12h0m0s
  vaultSecretDefinitions:
    - connection:
        address: {{ .Values.vault.address }}
      authentication:
        path: {{ .Values.vault.authPath }}
        role: {{ .Values.vault.role }}
        serviceAccount:
          name: default
      name: secret
      path: {{ .Values.vault.secretPath }}/egress-ui
  output:
    name: egress-ui-secret
    stringData:
      keycloakClientSecret: {{`'{{ .secret.keycloak_client_secret }}'`}}
    type: Opaque
{{- end }}
