apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: postgres-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshPeriod: 12h0m0s
  vaultSecretDefinitions:
    - authentication:
        path: {{ .Values.vault.authPath }}
        role: {{ .Values.vault.role }}
        serviceAccount:
          name: default
      name: secret
      path: {{ .Values.vault.secretPath }}/postgres
    {{- if .Values.postgres.backups.enabled }}
    - authentication:
        path: {{ .Values.vault.authPath }}
        role: {{ .Values.vault.role }}
        serviceAccount:
          name: default
      name: backup
      path: {{ .Values.postgres.backups.vault.path }}
    {{- end }}
  output:
    name: postgres-secret
    stringData:
      username: 'postgres'
      password: {{`'{{ .secret.postgres_password }}'`}}
      {{- if .Values.postgres.backups.enabled }}
      backupAccessKey: {{ printf "{{ .backup.%s }}" .Values.postgres.backups.vault.accessKeyField | squote }}
      backupSecretKey: {{ printf "{{ .backup.%s }}" .Values.postgres.backups.vault.secretKeyField | squote }}
      {{- end }}
    type: Opaque
