{{- if and .Values.vault.enabled .Values.seq.enabled }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: seq-admin-password-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshPeriod: 12h0m0s
  vaultSecretDefinitions:
    - authentication:
        path: {{ .Values.vault.authPath }}
        role: {{ .Values.vault.role }}
        serviceAccount:
          name: default
      name: secret
      path: {{ .Values.vault.secretPath }}/seq
  output:
    name: seq-admin-password-secret
    stringData:
      password: {{`'{{ .secret.admin_password }}'`}}
    type: Opaque
{{- end }}
