{{- if and .Values.vault.enabled .Values.submission.enabled }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: submission-api-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshPeriod: 12h0m0s
  vaultSecretDefinitions:
    - authentication:
        path: {{ .Values.vault.authPath }}
        role: {{ .Values.vault.role }}
        serviceAccount:
          name: default
      name: secret
      path: {{ .Values.vault.secretPath }}/submission-api
  output:
    name: submission-api-secret
    stringData:
      connectionString: {{`'{{ .secret.connection_string }}'`}}
      keycloakClientSecret: {{`'{{ .secret.keycloak_client_secret }}'`}}
      keycloakAdminUsername: {{`'{{ .secret.keycloak_admin_username }}'`}}
      keycloakAdminPassword: {{`'{{ .secret.keycloak_admin_password }}'`}}
      s3AccessKey: {{`'{{ .secret.s3_access_key }}'`}}
      s3SecretKey: {{`'{{ .secret.s3_secret_key }}'`}}
      rabbitUsername: {{`'{{ .secret.rabbit_username }}'`}}
      rabbitPassword: {{`'{{ .secret.rabbit_password }}'`}}
      vaultToken: {{`'{{ .secret.vault_token }}'`}}
    type: Opaque

---

apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: submission-ui-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshPeriod: 12h0m0s
  vaultSecretDefinitions:
    - authentication:
        path: {{ .Values.vault.authPath }}
        role: {{ .Values.vault.role }}
        serviceAccount:
          name: default
      name: secret
      path: {{ .Values.vault.secretPath }}/submission-ui
  output:
    name: submission-ui-secret
    stringData:
      keycloakClientSecret: {{`'{{ .secret.keycloak_client_secret }}'`}}
    type: Opaque
{{- end }}
