name: Build Agent Helm Chart

on:
  pull_request:
    paths:
      - '.github/workflows/agent-chart.yaml'
      - 'charts/agent/**'
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/agent-chart.yaml'
      - 'charts/agent/**'

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  agent-helm-chart:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-chart.yaml@v4.0.0-charts
    with:
      job-name: agent-helm-chart
      registry: ${{ vars.HARBOR_FEDA_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-project: ${{ vars.HARBOR_PROJECT }}
      registry-repo: agent
      release-tag-format: 'Agent-Chart-${version}'
      notation-cert: ${{ vars.NOTATION_CERT }}
      chart: charts/agent
      test-command: |
        helm template $CHART --debug
    secrets:
      notation-key: ${{ secrets.NOTATION_KEY }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
